openapi: 3.0.0
servers:
  - description: Financial Modeling Prep API
    url: https://financialmodelingprep.com/api/v3
info:
  description: Financial Modeling Prep API
  version: 1.0.0
  title: Financial Modeling Prep API
  contact:
    email: sam@sddproductions.com
  license:
    name: GPL-3.0
tags:
  - name: history
    description: History
  - name: company_valuation
    description: Company Valuation
  - name: list
    description: List
security:
  - api_key: []
paths:
  /profile/{symbol}:
    $ref: "./paths/profile.yaml"

  /{type}/list:
    $ref: "./paths/list.yaml"

  /historical-price-full/{symbol}:
    $ref: "./paths/historicalPriceFull.yaml"

  /historical-chart/{resolution}/{symbol}:
    $ref: "./paths/historicalChart.yaml"

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: apikey
      in: query
  schemas:
    Symbol:
      $ref: "./schemas/Symbol.yaml"
    EndOfDayPriceHistory:
      $ref: "./schemas/EndOfDayPriceHistory.yaml"
    EndOfDayPrice:
      $ref: "./schemas/EndOfDayPrice.yaml"
    OHVCVPrices:
      $ref: "./schemas/OHVCVPrices.yaml"
    OHVCVPrice:
      $ref: "./schemas/OHVCVPrice.yaml"
    CompanyProfile:
      $ref: "./schemas/CompanyProfile.yaml"









